[workspace]
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "colcon-fish"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=8.3.3,<9"
scspell3k = ">=2.2,<3"
pylint = ">=3.3.1,<4"
pytest-cov = ">=6.0.0,<7"
flake8 = ">=7.1.1,<8"
python = "<3.13"
colcon-core = ">=0.18.2,<0.19"
cmake = ">=4.2.0,<5"
pip = ">=25.3,<26"
